### ISSUE TITLE
LR and loss

### ISSUE THREAD

**Issue by johngrabner** [him4318/Transformer_ocr#1]
You are better than me, I tried a similar and it worked very bad.
I would love to learn from yours.

What LR did you use?
What loss vs epoch did you get?

**Comment by him4318** [comment]
Hi @johngrabner  you can look at the colab [link](https://colab.research.google.com/drive/1rCPaksWk7SAH4crOVYVzUaWsKbz2i3jE?authuser=1#scrollTo=rQew0_CkacDU).
