### ISSUE TITLE
TypeError: normalize() argument 2 must be str, not numpy.ndarray

### ISSUE THREAD

**Issue by corbinan** [him4318/Transformer_ocr#19]
Hi! I'm getting this error 
 TypeError: normalize() argument 2 must be str, not numpy.ndarray

for the line of code: 

        text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode("ascii")

Please help

**Comment by him4318** [comment]
Hi,
Can you check your data loader, this is with it only instead of text it is getting arrays.

**Comment by corbinan** [comment]
Hi thanks, what should I change?

**Comment by him4318** [comment]
You can try to put print statement in the get_item function of data loader.

```
    def __getitem__(self, i):
        img = self.dataset[self.split]['dt'][i]
        
        #making image compatible with resnet
        img = np.repeat(img[..., np.newaxis],3, -1)    
        img = pp.normalization(img)
        
        if self.transform is not None:
            img = self.transform(img)

        ###Here
        ###if it's array then change it accordingly in the code.
        print(self.dataset[self.split]['gt'][i])


        y_train = self.tokenizer.encode(self.dataset[self.split]['gt'][i]) 
        
        #padding till max length
        y_train = np.pad(y_train, (0, self.tokenizer.maxlen - len(y_train)))

        gt = torch.Tensor(y_train)

        return img, gt          

    def __len__(self):
      return self.size

```

**Comment by him4318** [comment]
Sorry closed it by mistake you can re-open it.

**Comment by corbinan** [comment]
Did that, it has printed an array of numbers 

![image](https://user-images.githubusercontent.com/108492156/176832454-79c0ff00-e14e-4345-9028-919690d19524.png)

How do I fix this in the data loader?

**Comment by him4318** [comment]
So it seems there is a problem with hdf5 itself, while creating it you have saved the integer values instead of text.

**Comment by corbinan** [comment]
I had run it like this:

`python3 main.py --source=bentham --transform
`

**Comment by corbinan** [comment]
Ran it again and this time I got this:

normalize() argument 2 must be str, not numpy.bytes_

From printing like you asked me to above, I get this:


![image](https://user-images.githubusercontent.com/108492156/176839015-578f3c95-4fc6-49b3-ade4-7ff5de803cfc.png)
