### ISSUE TITLE
Rimes Dataset Access

### ISSUE THREAD

**Issue by elnazsn1988** [him4318/Transformer_ocr#2]
HI @him4318 thanks for the repo, I have sent over an NDA ro the Rimes a2ai website but have not gotten access to it, if you have the data on a google drive, is there anyway I can get access to it?

**Comment by him4318** [comment]
Hi @elnazsn1988 
I did not try with the Rimes dataset, For data loading steps I used this [repo](https://github.com/arthurflor23/handwritten-text-recognition ).
