### ISSUE TITLE
Notebook loading error

### ISSUE THREAD

**Issue by hongzhenwang** [him4318/Transformer_ocr#4]
Hi，the notebook url can not open successfully. Could you add the notebook file in git project? Thanks.
![image](https://user-images.githubusercontent.com/9897079/103204460-62d12c00-4932-11eb-9c1b-d153bc4ead7f.png)

**Comment by fracav** [comment]
I have the same problem :).
I would also appreciate being able to use the notebook

**Comment by him4318** [comment]
Done!

**Comment by fracav** [comment]
thank you so much!
________________________________
Da: Himanshu Chaudhary <notifications@github.com>
Inviato: lunedì 8 marzo 2021 07:48
A: him4318/Transformer_ocr <Transformer_ocr@noreply.github.com>
Cc: FRANCESCO CAVINA <fra.cavina@stud.uniroma3.it>; Comment <comment@noreply.github.com>
Oggetto: Re: [him4318/Transformer_ocr] Notebook loading error (#4)


Done!
