### ISSUE TITLE
RuntimeError: shape '[-1, 100]' is invalid for input of size 201168

### ISSUE THREAD

**Issue by Alymostafa** [him4318/Transformer_ocr#5]
Hi. I ran the ```Transformer-ocr.ipynb``` file on Google Colab without making any edits. and yields an error at the start of training in, the modules in colab notebook isn't the same in the repo code.
![issue_@](https://user-images.githubusercontent.com/34445689/106365656-9f33e580-633f-11eb-9abc-c5fbed219828.png)

**Comment by him4318** [comment]
Hi @Alymostafa 
It was due to different vocab size as `tokenizer.vocab_size` value was 99 and I was converting it to tensor of size 100. I have made the changes, it should work fine now.
