### ISSUE TITLE
how to replace the training process of CNN(resnet101) with a pretrained one ?

### ISSUE THREAD

**Issue by OmarMohammed88** [him4318/Transformer_ocr#7]

**Comment by him4318** [comment]
Hi @OmarMohammed88  
you can change this line in the tutorial notebook to your pretrained model.
`self.backbone = resnet101()`

**Comment by OmarMohammed88** [comment]
thank u very much .. 
Another question, what is the type of decoding did u use, is it Beam search or greedy or best path decoding?

**Comment by him4318** [comment]
I used the normal one which is greedy

**Comment by OmarMohammed88** [comment]
is it possible to change the algorithm if so, how can I assess that component?

**Comment by him4318** [comment]
You have to write your own beam search function using the probabilities of output vocab.
