### ISSUE TITLE
Issue with the .hdf5 file

### ISSUE THREAD

**Issue by sbuitragoh** [him4318/Transformer_ocr#8]
Hi, 

I've been testing your code with my own dataset and everything seems fine before the run_epochs. For some reason, when I try to make the image compatible with the resnet, it says _**TypeError: byte indices must be integers or slices, not tuple**_.

I don't know if it's something related directly to the h5py or my images itself. The images, for what I can read, are storaged like _b'./data/lines/rm_149_077_021.png'_ (it's the place where I keep the line images of my dataset).

Thanks

**Comment by him4318** [comment]
Hi,
Can you check if the image is able to load as NumPy array or not?  
One more thing can you give the path of the images just as a simple string not with the symbol ```b``` as it converts it to bytes.

**Comment by sbuitragoh** [comment]
Hi, 

I'll check right now the path. For some reason it saves in that way.
How can I load any image from the hdf5 file?

**Comment by sbuitragoh** [comment]
cnt.

I checked every part but can't find why there's that _b_ in the string of the .hdf5 file. 
In the dataset it's like this:
_{'train': {'dt': ['./data/lines/rm_149_075_001.png', './data/lines/rm_149_075_005.png', ...}_, 
also
_type(ds.dataset['train']['dt'])
<class 'list'>_   and   
_type(ds.dataset['train']['dt'][0])
<class 'str'>_
But if I look inside the file, the string is like this:
_hf[i]['dt'][0]
b'./data/lines/rm_149_075_001.png'_

Sadly, still can't find a way to change it.

**Comment by him4318** [comment]
In the  Data Generator class can you look in the ```__getitem__``` function and check ``` img = self.dataset[self.split]['dt'][i]``` this line, as this is the line where image is being read from the hdf5 file. you can print the shape of the array and see if it is properly loaded or not.

**Comment by sbuitragoh** [comment]
I guess it's not loaded correctly since img has class bytes. As I read, the hdf5 file should contain the numpy array of the image but I only have the string (who mysteriously transforms into bytes). Is it to crazy if I load the image using opencv, changing the bytes to string?

**Comment by him4318** [comment]
There is no need to create hdf5 file if it is creating issue for you. You can directly read an image using open CV and perform same pre-processing on it and send it to generator. For pre-processing step you can look at Single_inference_image function in engine.py to get some idea.

**Comment by sbuitragoh** [comment]
It seems is the hdf5 file. I'll be handling all of it directly with opencv.
Thanks.
